### ISSUE TITLE
Apple Mach-O Linker (ld) Error Group

### ISSUE THREAD

**Issue by phongle6893** [3ph/RxWifi#1]
## Run with iPhone 📱
It have one issue: 🐞 linker command failed with exit code 1 (use -v to see invocation)
<img width="272" alt="screen shot 2017-12-18 at 9 32 46 pm" src="https://user-images.githubusercontent.com/22513100/34111059-21fcc928-e43b-11e7-956b-82b71eb1904a.png">

## Run with simulator 
⚠️ Xcode does not warn about any problem at build time, but have some problem in run time 😢
### consol log 
It's related to XCtest, but I don't use it. I don't know why!
```swift =
dyld: Library not loaded: @rpath/XCTest.framework/XCTest
  Referenced from: /Users/phongle/Library/Developer/CoreSimulator/Devices/0739AAD9-5EE7-4B96-9370-0732759FE28E/data/Containers/Bundle/Application/413AECB2-75CB-4556-87D2-2D64A619E0FC/configWifi.app/Frameworks/libswiftXCTest.dylib
  Reason: image not found
(lldb)
```

### Thread 1: signal SIGABRT:
```swift =
dyld`__abort_with_payload:
    0x11e63320c <+0>:  movl   $0x2000209, %eax          ; imm = 0x2000209 
    0x11e633211 <+5>:  movq   %rcx, %r10
    0x11e633214 <+8>:  syscall 
->  0x11e633216 <+10>: jae    0x11e633220               ; <+20>
    0x11e633218 <+12>: movq   %rax, %rdi
    0x11e63321b <+15>: jmp    0x11e632a74               ; cerror_nocancel
    0x11e633220 <+20>: retq   
    0x11e633221 <+21>: nop    
    0x11e633222 <+22>: nop    
    0x11e633223 <+23>: nop    
```
Thank you!

**Comment by 3ph** [comment]
Ok did some investigation - looks like I've accidentally included RxNimble dependency in the main project (which would pull in XCTest). I've released new version 0.0.3 version with this fix.

Please give it a try.

**Comment by phongle6893** [comment]
Thank you ^^.
I have a question, how to add the Hotspot Configuration to my App id?
<img width="744" alt="screen shot 2017-12-21 at 11 15 38 pm" src="https://user-images.githubusercontent.com/22513100/34264767-7e58a968-e6a6-11e7-99c2-3c67aca63bcd.png">
I can't find it my app.
<img width="743" alt="screen shot 2017-12-21 at 11 15 00 pm" src="https://user-images.githubusercontent.com/22513100/34264663-2eed063a-e6a6-11e7-9327-5c4b77bd5fb4.png">

**Comment by 3ph** [comment]
You need to sign your the project (using your development team) otherwise you can only run it in simulator. Go to your targets, select the `RxWifi_Example` and select a team in the `Signing` section of the `General` tab. That should fix it I believe.
